### ISSUE TITLE
Use of uninitialized memory in __interceptor_fwrite

### ISSUE THREAD

**Issue by Mark-Boger** [libcheck/check#235]
Using llvms Memory Sanitizer on a minimal test suit warns of uninitialized memory.

### Code
```
#include <check.h>
#include <stdlib.h>
#include <stdint.h>
#include <broadcast_lang.h>

Suite * broadcast_lang_suite(void);

START_TEST(read_single_unit) {
    ck_assert_int_eq(1,1);
}
END_TEST


Suite * broadcast_lang_suite(void) {
    Suite *s;
    TCase *tc_core;

    s = suite_create("Broadcast Language Test Suite");
    tc_core = tcase_create("Parsing test cases");

    tcase_add_test(tc_core, read_single_unit);

    suite_add_tcase(s, tc_core);

    return s;
}

int main(void) {
    int failed;

    SRunner *sr;

    sr = srunner_create(broadcast_lang_suite());
    srunner_run_all(sr, CK_VERBOSE);

    failed = srunner_ntests_failed(sr);
    srunner_free(sr);

    return (failed == 0) ? EXIT_SUCCESS : EXIT_FAILURE;
};
```

### Output
```
Running suite(s): Broadcast Language Test Suite
Uninitialized bytes in __interceptor_fwrite at offset 0 inside [0x7010000000e0, 8)==118804==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7fade6d6d7e0  (/usr/lib/libcheck.so.0+0x47e0)
    #1 0x7fade6d6cf90  (/usr/lib/libcheck.so.0+0x3f90)
    #2 0x7fade6d6e5c6  (/usr/lib/libcheck.so.0+0x55c6)
    #3 0x7fade6d6edb2 in srunner_run_tagged (/usr/lib/libcheck.so.0+0x5db2)
    #4 0x563feef65b65 in main build/../test/grammatical_tests.c:10:5
    #5 0x7fade6a35152 in __libc_start_main (/usr/lib/libc.so.6+0x27152)
    #6 0x563feeeea12d in _start (bin/grammatical_tests+0x2012d)

SUMMARY: MemorySanitizer: use-of-uninitialized-value (/usr/lib/libcheck.so.0+0x47e0) 
Exiting
check_msg.c:133: Error in call to punpack
```

**Comment by mikkoi** [comment]
I created a test project and can reproduce the same error.
I compiled libcheck with the same options but couldn't discover the exact location of the error.

**Comment by mikkoi** [comment]
Running the libcheck's own tests also shows errors.
