### ISSUE TITLE
ASAN reporting memory leak inside libcheck

### ISSUE THREAD

**Issue by vykt** [libcheck/check#358]
## environment

**GCC**:   gcc-13.3.1_p20241025
**LIBC**:  GNU C Library (Gentoo 2.40-r5 (patchset 5)) stable release version 2.40
**OS**:    Gentoo Linux (default amd64, profile 23.0)
**CHECK**: [check-0.15.2-r1](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-libs/check/check-0.15.2-r1.ebuild)

## build

```
# Unit tests
CC=gcc
CFLAGS= -ggdb -Wall -fsanitize=address
LDFLAGS= -L${LIB_BIN_DIR} -Wl,-rpath=${LIB_BIN_DIR} -lcmore -lcheck -static-libasan
# -lcmore = library being unit tested

```
```
# Libcmore
CC=gcc
CFLAGS= -ggdb -Wall -Wextra -O0 -fsanitize=address
LDFLAGS= -static-libasan
```

## unit tests
```
// check_list.c
TCase * tc_new_list;
Suite * s = suite_create("list");
tc_new_list = tcase_create("new_list");
tcase_add_test(tc_new_list, test_new_list);
suite_add_tcase(s, tc_new_list);
return s;
```

```
// main.c
Suite * s_list;
SRunner * sr;
s_list = list_suite();
sr = srunner_create(s_list);
srunner_run_all(sr, CK_VERBOSE);
srunner_free(sr);
```

## case 1: CK_FORK=yes
```
$ ./unit_tests
Running suite(s): list

=================================================================
==12091==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 720 byte(s) in 10 object(s) allocated from:
    #0 0x55a068e6d79f in __interceptor_malloc /var/tmp/portage/sys-devel/gcc-13.3.1_p20241025/work/gcc-13-20241025/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7fa16440be4c in emalloc (/usr/lib64/libcheck.so.0+0x4e4c)

Indirect leak of 2480 byte(s) in 150 object(s) allocated from:
    #0 0x55a068e6d79f in __interceptor_malloc /var/tmp/portage/sys-devel/gcc-13.3.1_p20241025/work/gcc-13-20241025/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7fa16440be4c in emalloc (/usr/lib64/libcheck.so.0+0x4e4c)

SUMMARY: AddressSanitizer: 3200 byte(s) leaked in 160 allocation(s).
0%: Checks: 1, Failures: 0, Errors: 1
check_list.c:152:E:new_list:test_new_list:0: (after this point) Early exit with return value 1

=================================================================
==12090==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 720 byte(s) in 10 object(s) allocated from:
    #0 0x55a068e6d79f in __interceptor_malloc /var/tmp/portage/sys-devel/gcc-13.3.1_p20241025/work/gcc-13-20241025/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7fa16440be4c in emalloc (/usr/lib64/libcheck.so.0+0x4e4c)

Indirect leak of 2480 byte(s) in 150 object(s) allocated from:
    #0 0x55a068e6d79f in __interceptor_malloc /var/tmp/portage/sys-devel/gcc-13.3.1_p20241025/work/gcc-13-20241025/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7fa16440be4c in emalloc (/usr/lib64/libcheck.so.0+0x4e4c)

SUMMARY: AddressSanitizer: 3200 byte(s) leaked in 160 allocation(s).
```

## case 2: CK_FORK=no
```
$ ./unit_tests
Running suite(s): list
100%: Checks: 1, Failures: 0, Errors: 0
check_list.c:152:P:new_list:test_new_list:0: Passed

=================================================================
==13954==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 720 byte(s) in 10 object(s) allocated from:
    #0 0x55a368eed79f in __interceptor_malloc /var/tmp/portage/sys-devel/gcc-13.3.1_p20241025/work/gcc-13-20241025/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7f4f3469fe4c in emalloc (/usr/lib64/libcheck.so.0+0x4e4c)

Indirect leak of 2480 byte(s) in 150 object(s) allocated from:
    #0 0x55a368eed79f in __interceptor_malloc /var/tmp/portage/sys-devel/gcc-13.3.1_p20241025/work/gcc-13-20241025/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7f4f3469fe4c in emalloc (/usr/lib64/libcheck.so.0+0x4e4c)

SUMMARY: AddressSanitizer: 3200 byte(s) leaked in 160 allocation(s).
```

## discussion

The unit test and the functions called inside the unit test **never call malloc()**. When adding a dangling malloc() call, ASAN correctly reports an additional memory leak inside the unit test sources. As you can see, the memory leaks reported here originate **inside libcheck.so itself**.

When forking is used, there are two additional memory leaks and the test fails. Without forking the test succeeds.

I have spoken to Sam (nick: 'sam_'), a prominent Gentoo maintainer, in the #gentoo channel on LiberaIRC. He told me Gentoo's packaging of libcheck does not introduce any patches that could cause this. 

The example provided here shows just one unit test. For the full test sources, see [libcmore's tests directory](github.com/vykt/libcmore/tree/main/src/test).

Note that the vector tests succeed in both forking and non-forking mode without any leaks reported by ASAN.

**Comment by vykt** [comment]
User error.
